[build]
  command = "npm run build"
  publish = "public/dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[build.environment]
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions", "@sendgrid/mail", "zod"]
  node_bundler_options = { format = "cjs", target = "node18" }

[functions.environment]
  NODE_ENV = "production"
